In [1]:
import numpy as np

In [9]:
l = [1,2,3,4]
arr =np.array(l)

In [11]:
type(arr)


numpy.ndarray

In [15]:
l1 = [1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[3,4,5,6,7]
arr1 =np.array([l1,l2,l3])

In [17]:
arr1.shape


(3, 5)

In [19]:
# indexing

In [23]:
arr[3]


4

In [29]:
arr[1:3]   #n-1

array([2, 3])

In [31]:
arr[-1]

4

In [33]:
arr[:-1]# removes last element

array([1, 2, 3])

In [35]:
arr[::-1]  # for rversing

array([4, 3, 2, 1])

In [37]:
arr[::-2]  # jump 2 elements

array([4, 2])

In [39]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [41]:
arr1[:,1]  # all rows and 1th column

array([2, 3, 4])

In [43]:
arr1[1:,1:3]  # : use for badke elements

array([[3, 4],
       [4, 5]])

In [47]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [53]:
arr1[1:,2:].shape

(2, 3)

In [199]:
#EDA
arr

array([1, 2, 3, 4])

In [193]:
arr<2

array([ True, False, False, False])

In [201]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [203]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [205]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [209]:
arr1*arr1  # sqaure of whole array

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [211]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [213]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [233]:
np.random.randint(10,15,2)


array([11, 14])

np.random.randn(5,6)

In [235]:
np.random.randn(4,6)

array([[ 2.38726084, -0.36098518, -0.56379305, -0.86850215,  1.4056383 ,
         0.17580568],
       [-2.05155378,  2.07146809,  0.54134134,  0.55427107, -1.43708877,
         0.76203448],
       [ 0.45441865,  0.29178   ,  1.44534428,  0.1855038 ,  0.39091184,
         0.11779719],
       [ 1.37131119,  1.19323309,  0.57709343, -0.60438594, -0.46826625,
        -2.59534673]])

In [237]:
np.random.random_sample((4,3))  # craete a array btwn 0-1

array([[0.72768752, 0.09517691, 0.27661982],
       [0.41123838, 0.18828614, 0.90614617],
       [0.22129942, 0.28268916, 0.37894972],
       [0.81091499, 0.28025335, 0.92672053]])